git:
 submodules: false

language: c

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env: RID=linux-x64
    - os: linux
      dist: trusty
      sudo: required
      env: RID=linux-musl-x64
    - os: osx
      env: RID=osx

branches:
 only:
   - master
   - /^maint.*/

before_install:
 - date -u
 - uname -a
 - env | grep -v "BINTRAY_API_KEY" | sort
 - git submodule update --init

install: true

script: if [[ $RID == "osx" ]]; then ./build.libgit2.sh ; else ./dockerbuild.sh ; fi

after_success: ./uploadbinaries.sh
